## Anand Chandak

We are going to develop traing and test set which will used for creating machine 
learning model to predict flight price. For this, we have data of flight which includes
name of company, depart time, arrival time, journey time, price, route, stopage, feedback, etc

In [1]:
# importing the necessaru package and creating the test and train data sets
import pandas as pd

training_set = pd.read_excel("Data_Train.xlsx")
test_set = pd.read_excel("Test_set.xlsx")

In [2]:
training_set.head() # seeing how the training data looks

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897  
1    05:50         13:15   7h 25m     2 stops         No info   7662  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882  
3    18:05         23:30   5h 25m      1 stop         No info   6218  
4    16:50         21:35   4h 45m      1 stop         No info  13302

In [6]:
# printing the details about training dataset

print("#"*30)
print("\n EDA on Training set\n")
print("#"*30)

print("\nFeatures / Columns: \n", training_set.columns)
print("\nNumber of features and columns: ", len(training_set.columns))
print("\nNumber of rows: ", len(training_set))
print("\nDatatypes of columns:\n", training_set.dtypes)
print("\nContains Nan or Empty values: ", training_set.isnull().values.any())
print("\nTotal Empty cells by columns: \n", training_set.isnull().sum(), "\n\n")


##############################

 EDA on Training set

##############################

Features / Columns: 
 Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

Number of features and columns:  11

Number of rows:  10683

Datatypes of columns:
 Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

Contains Nan or Empty values:  True

Total Empty cells by columns: 
 Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64 



In [7]:
# printing the details of test dataset
print("#"*30)
print("\nEDA on test set\n")
print("#"*30)

print("\nFeatures/Columns:\n", test_set.columns)
print("\nNumbers of features and columns: ", len(test_set.columns))
print("\nNumber of rows: ", len(test_set))
print("\nDatatypes of columns:\n ", test_set.dtypes)
print("\nContains Nan values or empty values: ", test_set.isna().values.any())
print("\nTotal empty cells by columns: \n", test_set.isna().sum())

##############################

EDA on test set

##############################

Features/Columns:
 Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info'],
      dtype='object')

Numbers of features and columns:  10

Number of rows:  2671

Datatypes of columns:
  Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
dtype: object

Contains Nan values or empty values:  False

Total empty cells by columns: 
 Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
dtype: int64


In [9]:
print("Original number of rows: ", len(training_set))
training_set.dropna(inplace=True)   # dropping null values, as there is only one null value
print("After dropping Null, number of rows: ", len(training_set))

Original number of rows:  10683
After dropping Null, number of rows:  10682


In [10]:
# converting datatype to date and time format and adding new columns

training_set["Journey_Day"]= pd.to_datetime(training_set["Date_of_Journey"], format="%d/%m/%Y").dt.day
training_set.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   Journey_Day  
0           24  
1            1  
2            9  
3           12  
4            1

In [11]:
training_set["Journey_Month"]= pd.to_datetime(training_set["Date_of_Journey"], format="%d/%m/%Y").dt.month
training_set.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   Journey_Day  Journey_Month  
0           24              3  
1            1              5  
2            9              6  
3           12              5  
4            1              3

In [12]:
# Similarly, we are going to creat day and month columns from Date_of_Jouney column and then 
# will drop it

In [13]:
try:
    test_set["Journey_Day"]= pd.to_datetime(test_set["Date_of_Journey"], format="%d/%m/%Y").dt.day
    test_set["Journey_Month"]= pd.to_datetime(test_set["Date_of_Journey"], format="%d/%m/%Y").dt.month
    
    display(test_set.head())   # checking the test dataset
except Exception as e:
    print(e)

Airline Date_of_Journey    Source Destination            Route  \
0        Jet Airways       6/06/2019     Delhi      Cochin  DEL → BOM → COK   
1             IndiGo      12/05/2019   Kolkata    Banglore  CCU → MAA → BLR   
2        Jet Airways      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
3  Multiple carriers      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
4           Air Asia      24/06/2019  Banglore       Delhi        BLR → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops              Additional_Info  \
0    17:30  04:25 07 Jun  10h 55m      1 stop                      No info   
1    06:20         10:20       4h      1 stop                      No info   
2    19:15  19:00 22 May  23h 45m      1 stop  In-flight meal not included   
3    08:00         21:00      13h      1 stop                      No info   
4    23:55  02:45 25 Jun   2h 50m    non-stop                      No info   

   Journey_Day  Journey_Month  
0            6              6  
1           12              5  
2           21              5  
3           21              5  
4           24              6

In [15]:
# Now, we dont't need original date column, so going to drop it

# train set
print("Column count in train set: ", len(training_set.columns))
training_set.drop(labels="Date_of_Journey", axis=1, inplace=True)
print("Column count after deletion: ", len(training_set.columns))

print("-------------------------------------------------------------")
# test set
print("Column Count in test set: ", len(test_set.columns))
test_set.drop(labels="Date_of_Journey", axis=1, inplace=True)
print("Column count after deletion: ", len(test_set.columns))

Column count in train set:  13
Column count after deletion:  12
-------------------------------------------------------------
Column Count in test set:  12
Column count after deletion:  11


In [16]:
training_set.head()

Airline    Source Destination                  Route Dep_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR    18:05   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL    16:50   

   Arrival_Time Duration Total_Stops Additional_Info  Price  Journey_Day  \
0  01:10 22 Mar   2h 50m    non-stop         No info   3897           24   
1         13:15   7h 25m     2 stops         No info   7662            1   
2  04:25 10 Jun      19h     2 stops         No info  13882            9   
3         23:30   5h 25m      1 stop         No info   6218           12   
4         21:35   4h 45m      1 stop         No info  13302            1   

   Journey_Month  
0              3  
1              5  
2              6  
3              5  
4              3

In [17]:
test_set.head()

Airline    Source Destination            Route Dep_Time  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK    17:30   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR    06:20   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK    19:15   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK    08:00   
4           Air Asia  Banglore       Delhi        BLR → DEL    23:55   

   Arrival_Time Duration Total_Stops              Additional_Info  \
0  04:25 07 Jun  10h 55m      1 stop                      No info   
1         10:20       4h      1 stop                      No info   
2  19:00 22 May  23h 45m      1 stop  In-flight meal not included   
3         21:00      13h      1 stop                      No info   
4  02:45 25 Jun   2h 50m    non-stop                      No info   

   Journey_Day  Journey_Month  
0            6              6  
1           12              5  
2           21              5  
3           21              5  
4           24              6

In [19]:
# Our duration column has time written in format like 03h 40m
# To help machine learning algorithm derive useful insights, we will convert this text into 
# numerical type

duration = list(training_set["Duration"])

for i in range(len(training_set)):
    if len(duration[i].split()) < 2:
        if 'h' or 'H' in duration[i]:
            duration[i] = duration[i].strip() + " 0m"
        elif 'm' or 'M' in duration[i]:
            duration[i] = "0h {}". format(duration[i].strip())

In [20]:
duration

['2h 50m',
 '7h 25m',
 '19h 0m',
 '5h 25m',
 '4h 45m',
 '2h 25m',
 '15h 30m',
 '21h 5m',
 '25h 30m',
 '7h 50m',
 '13h 15m',
 '2h 35m',
 '2h 15m',
 '12h 10m',
 '2h 35m',
 '26h 35m',
 '4h 30m',
 '22h 35m',
 '23h 0m',
 '20h 35m',
 '5h 10m',
 '15h 20m',
 '2h 50m',
 '2h 55m',
 '13h 20m',
 '15h 10m',
 '5h 45m',
 '5h 55m',
 '2h 50m',
 '2h 15m',
 '2h 15m',
 '13h 25m',
 '2h 50m',
 '22h 0m',
 '5h 30m',
 '10h 25m',
 '5h 15m',
 '2h 30m',
 '6h 15m',
 '11h 55m',
 '11h 5m',
 '8h 30m',
 '22h 5m',
 '2h 45m',
 '12h 0m',
 '2h 50m',
 '2h 50m',
 '2h 15m',
 '16h 5m',
 '19h 55m',
 '3h 15m',
 '25h 20m',
 '2h 50m',
 '3h 0m',
 '2h 50m',
 '16h 15m',
 '15h 5m',
 '2h 15m',
 '6h 30m',
 '25h 5m',
 '12h 25m',
 '27h 20m',
 '10h 15m',
 '10h 30m',
 '2h 15m',
 '10h 25m',
 '2h 50m',
 '1h 30m',
 '13h 20m',
 '2h 15m',
 '1h 25m',
 '26h 30m',
 '7h 20m',
 '13h 30m',
 '5h 0m',
 '2h 45m',
 '2h 50m',
 '1h 30m',
 '19h 5m',
 '2h 15m',
 '14h 50m',
 '2h 40m',
 '22h 10m',
 '9h 35m',
 '10h 0m',
 '21h 20m',
 '5h 25m',
 '18h 45m',
 '12h 

In [22]:
dur_hours = []
dur_minute = []

for i in range(len(training_set)):
    dur_hours.append(int(duration[i].split()[0][:-1])) 
    dur_minute.append(int(duration[i].split()[1][:-1]))
    
# In duration list all the values are in string type. After discarding h and m of hour and minu 
# respectively, the numbers will remain which also will be in string type. Since numbers can't be in string 
# type, so we typecast then in int and stored in list datastructure.

training_set["Duration_Hours"] = dur_hours
training_set["Duration_Minutes"] = dur_minute

In [24]:
training_set.drop(labels="Duration", axis=1, inplace=True)

In [25]:
# As we did with Duration column of training set, The same will be performed on Duration column
# of test set

durationT = list(test_set["Duration"])

for i in range(len(test_set)):
    if len(durationT[i].split()) < 2:
        if 'h' or 'H' in durationT[i]:
            durationT[i] = durationT[i].strip() + " 0m"
        elif 'm' or 'M' in durationT[i]:
            durationT[i] = "0h {}" .format(durationT[i].strip())

dur_h = []
dur_m =[]

for i in range(len(durationT)):
    dur_h.append(int(durationT[i].split()[0][:-1]))
    dur_m.append(int(durationT[i].split()[1][:-1]))

test_set["Duration_Hours"]= dur_h
test_set["Duration_Minute"]=dur_m 

In [26]:
test_set.drop(labels="Duration", axis=1, inplace=True)

In [27]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2671 entries, 0 to 2670
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          2671 non-null   object
 1   Source           2671 non-null   object
 2   Destination      2671 non-null   object
 3   Route            2671 non-null   object
 4   Dep_Time         2671 non-null   object
 5   Arrival_Time     2671 non-null   object
 6   Total_Stops      2671 non-null   object
 7   Additional_Info  2671 non-null   object
 8   Journey_Day      2671 non-null   int64 
 9   Journey_Month    2671 non-null   int64 
 10  Duration_Hours   2671 non-null   int64 
 11  Duration_Minute  2671 non-null   int64 
dtypes: int64(4), object(8)
memory usage: 250.5+ KB


In [28]:
#Converting 'Dep_Time' to 'Depart_Time_hour' and 'Depart_time_Minutes'
training_set['Depart_Time_Hour'] = pd.to_datetime(training_set.Dep_Time).dt.hour
training_set['Depart_Time_Minutes'] = pd.to_datetime(training_set.Dep_Time).dt.minute

training_set.drop(labels = 'Dep_Time', axis = 1, inplace = True)

training_set.head() # cheking the training set after transformation

Airline    Source Destination                  Route  Arrival_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL  01:10 22 Mar   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR         13:15   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK  04:25 10 Jun   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR         23:30   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL         21:35   

  Total_Stops Additional_Info  Price  Journey_Day  Journey_Month  \
0    non-stop         No info   3897           24              3   
1     2 stops         No info   7662            1              5   
2     2 stops         No info  13882            9              6   
3      1 stop         No info   6218           12              5   
4      1 stop         No info  13302            1              3   

   Duration_Hours  Duration_Minutes  Depart_Time_Hour  Depart_Time_Minutes  
0               2                50                22                   20  
1               7                25                 5                   50  
2              19                 0                 9                   25  
3               5                25                18                    5  
4               4                45                16                   50

In [29]:
#Converting 'Arr_Time' to 'Arr_Time_hour' and 'Arr_time_Minutes' and dropping the original column
training_set['Arr_Time_Hour'] = pd.to_datetime(training_set.Arrival_Time).dt.hour
training_set['Arr_Time_Minutes'] = pd.to_datetime(training_set.Arrival_Time).dt.minute

training_set.drop(labels = 'Arrival_Time', axis = 1, inplace = True)
training_set.head() # cheking the training set after transformation

Airline    Source Destination                  Route Total_Stops  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    non-stop   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR     2 stops   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK     2 stops   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR      1 stop   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL      1 stop   

  Additional_Info  Price  Journey_Day  Journey_Month  Duration_Hours  \
0         No info   3897           24              3               2   
1         No info   7662            1              5               7   
2         No info  13882            9              6              19   
3         No info   6218           12              5               5   
4         No info  13302            1              3               4   

   Duration_Minutes  Depart_Time_Hour  Depart_Time_Minutes  Arr_Time_Hour  \
0                50                22                   20              1   
1                25                 5                   50             13   
2                 0                 9                   25              4   
3                25                18                    5             23   
4                45                16                   50             21   

   Arr_Time_Minutes  
0                10  
1                15  
2                25  
3                30  
4                35

In [30]:
# applying the same to test set
test_set['Depart_Time_Hour'] = pd.to_datetime(test_set.Dep_Time).dt.hour
test_set['Depart_Time_Minutes'] = pd.to_datetime(test_set.Dep_Time).dt.minute


test_set.drop(labels = 'Dep_Time', axis = 1, inplace = True)
test_set.head() # cheking the test set after transformation

Airline    Source Destination            Route  Arrival_Time  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK  04:25 07 Jun   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR         10:20   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK  19:00 22 May   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK         21:00   
4           Air Asia  Banglore       Delhi        BLR → DEL  02:45 25 Jun   

  Total_Stops              Additional_Info  Journey_Day  Journey_Month  \
0      1 stop                      No info            6              6   
1      1 stop                      No info           12              5   
2      1 stop  In-flight meal not included           21              5   
3      1 stop                      No info           21              5   
4    non-stop                      No info           24              6   

   Duration_Hours  Duration_Minute  Depart_Time_Hour  Depart_Time_Minutes  
0              10               55                17                   30  
1               4                0                 6                   20  
2              23               45                19                   15  
3              13                0                 8                    0  
4               2               50                23                   55

In [31]:
test_set['Arr_Time_Hour'] = pd.to_datetime(test_set.Arrival_Time).dt.hour
test_set['Arr_Time_Minutes'] = pd.to_datetime(test_set.Arrival_Time).dt.minute

test_set.drop(labels = 'Arrival_Time', axis = 1, inplace = True)
test_set.head() # cheking the test set after transformation

Airline    Source Destination            Route Total_Stops  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK      1 stop   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR      1 stop   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK      1 stop   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK      1 stop   
4           Air Asia  Banglore       Delhi        BLR → DEL    non-stop   

               Additional_Info  Journey_Day  Journey_Month  Duration_Hours  \
0                      No info            6              6              10   
1                      No info           12              5               4   
2  In-flight meal not included           21              5              23   
3                      No info           21              5              13   
4                      No info           24              6               2   

   Duration_Minute  Depart_Time_Hour  Depart_Time_Minutes  Arr_Time_Hour  \
0               55                17                   30              4   
1                0                 6                   20             10   
2               45                19                   15             19   
3                0                 8                    0             21   
4               50                23                   55              2   

   Arr_Time_Minutes  
0                25  
1                20  
2                 0  
3                 0  
4                45

In [32]:
Y_train = training_set.iloc[:,6].values  # 6 is the index of "Price" in the Training Set , setting it as the label column

# Independent Variables
X_train = training_set.iloc[:,training_set.columns != 'Price'].values # selects all columns except "Price"

# Independent Variables for Test Set
X_test = test_set.iloc[:,:].values

X_train

array([['IndiGo', 'Banglore', 'New Delhi', ..., 20, 1, 10],
       ['Air India', 'Kolkata', 'Banglore', ..., 50, 13, 15],
       ['Jet Airways', 'Delhi', 'Cochin', ..., 25, 4, 25],
       ...,
       ['Jet Airways', 'Banglore', 'Delhi', ..., 20, 11, 20],
       ['Vistara', 'Banglore', 'New Delhi', ..., 30, 14, 10],
       ['Air India', 'Delhi', 'Cochin', ..., 55, 19, 15]], dtype=object)

In [33]:
# From the info above it could be observed that many colmns are of object type. So, converting those categorical columns to numerical columns
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()

In [35]:
# training set

In [36]:
X_train[:,0] = le1.fit_transform(X_train[:,0])
X_train

array([[3, 'Banglore', 'New Delhi', ..., 20, 1, 10],
       [1, 'Kolkata', 'Banglore', ..., 50, 13, 15],
       [4, 'Delhi', 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 'Banglore', 'Delhi', ..., 20, 11, 20],
       [10, 'Banglore', 'New Delhi', ..., 30, 14, 10],
       [1, 'Delhi', 'Cochin', ..., 55, 19, 15]], dtype=object)

In [37]:
X_train[:,1] = le1.fit_transform(X_train[:,1])
X_train

array([[3, 0, 'New Delhi', ..., 20, 1, 10],
       [1, 3, 'Banglore', ..., 50, 13, 15],
       [4, 2, 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 0, 'Delhi', ..., 20, 11, 20],
       [10, 0, 'New Delhi', ..., 30, 14, 10],
       [1, 2, 'Cochin', ..., 55, 19, 15]], dtype=object)

In [38]:
X_train[:,2] = le1.fit_transform(X_train[:,2])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [39]:
X_train[:,3] = le1.fit_transform(X_train[:,3])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [40]:
X_train[:,4] = le1.fit_transform(X_train[:,4])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [41]:
X_train[:,5] = le1.fit_transform(X_train[:,5])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [42]:
# Applying similar operation on test set using for loop

In [43]:
for i in range(6):
    X_test[:,i] = le2.fit_transform(X_test[:,i])
X_test

array([[4, 2, 1, ..., 30, 4, 25],
       [3, 3, 0, ..., 20, 10, 20],
       [4, 2, 1, ..., 15, 19, 0],
       ...,
       [4, 2, 1, ..., 50, 4, 25],
       [1, 2, 1, ..., 0, 19, 15],
       [6, 2, 1, ..., 55, 19, 15]], dtype=object)

In [44]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

In [45]:
X_train = sc_X.fit_transform(X_train)
X_train

array([[-0.41080484, -1.65835945,  2.41653414, ..., -0.2349499 ,
        -1.80043628, -0.8900139 ],
       [-1.26115217,  0.89001433, -0.97381203, ...,  1.36360731,
        -0.05090913, -0.5870944 ],
       [ 0.01436882,  0.04055641, -0.2957428 , ...,  0.0314763 ,
        -1.3630545 ,  0.0187446 ],
       ...,
       [ 0.01436882, -1.65835945,  0.38232644, ..., -0.2349499 ,
        -0.34249699, -0.2841749 ],
       [ 2.56541078, -1.65835945,  2.41653414, ...,  0.2979025 ,
         0.0948848 , -0.8900139 ],
       [-1.26115217,  0.04055641, -0.2957428 , ...,  1.63003351,
         0.82385444, -0.5870944 ]])

In [46]:
X_test = sc_X.transform(X_test)
X_test

array([[ 0.01436882,  0.04055641, -0.2957428 , ...,  0.2979025 ,
        -1.3630545 ,  0.0187446 ],
       [-0.41080484,  0.89001433, -0.97381203, ..., -0.2349499 ,
        -0.48829092, -0.2841749 ],
       [ 0.01436882,  0.04055641, -0.2957428 , ..., -0.5013761 ,
         0.82385444, -1.4958529 ],
       ...,
       [ 0.01436882,  0.04055641, -0.2957428 , ...,  1.36360731,
        -1.3630545 ,  0.0187446 ],
       [-1.26115217,  0.04055641, -0.2957428 , ..., -1.30065471,
         0.82385444, -0.5870944 ],
       [ 0.86471614,  0.04055641, -0.2957428 , ...,  1.63003351,
         0.82385444, -0.5870944 ]])

In [47]:
# applying similar operation on the Y labels
Y_train = Y_train.reshape((len(Y_train), 1)) 
Y_train = sc_X.fit_transform(Y_train)
Y_train = Y_train.ravel()
Y_train

array([-1.12553455, -0.30906781,  1.03978296, ..., -0.40296691,
        0.77218138,  0.57809433])

We have our training and test data sets sepearted which can be used to buils a machine learning model now.

###### Thank you